menus:
  home: /
  categories: /categories
  tags: /tags
  about: /about

# chrome toolbar color for android chrome
theme_color: f5f5f5

# site's favicon
favicon: favicon.png

# google site verification code's content
google_site_verification: c66gcm0iMw487a2YC6w7cFbrhhe_Mh_vVNC6Pt3Dak8

post_toc: false

is_show_categories: true

is_show_tags: true
