menu:
  Home: /
#  Archives: /archives
  Categories: /categories
  Tags: /tags
  About: /about
#  Github: https://github.com/varzy

theme_color: '#f5f5f5'

favicon: 'favicon.png'

google_site_verification: c66gcm0iMw487a2YC6w7cFbrhhe_Mh_vVNC6Pt3Dak8